Update to wifi.cgi and setup
Uploaded so I don't lose changes. Having lots of problems at the moment with piCorePlayer.

diff --git a/pcp/sbin/setup b/pcp/sbin/setup
--- a/pcp/sbin/setup
+++ b/pcp/sbin/setup
@@ -1,6 +1,6 @@
 #!/bin/sh +x
 
-# Version: 0.02 2015-08-17 GE
+# Version: 0.02 2015-08-19 GE
 #	Updated.
 
 # Version: 0.01 2015-05-19 GE
@@ -20,6 +20,10 @@ DIALOG_HELP=2
 DIALOG_EXTRA=3
 DIALOG_ITEM_HELP=4
 DIALOG_ESC=255
+
+WIFICHANGED=0
+STATICIPCHANGED=0
+WEBGUICHANGED=0
 
 #========================================================================================
 # Check if dialog.tcz is installed - install if necessary.
@@ -54,9 +58,31 @@ pcp_start_message() {
 	[ $? = $DIALOG_OK ] || pcp_exit_program
 }
 
+#========================================================================================
+# Exit
+#----------------------------------------------------------------------------------------
 pcp_exit_program() {
 	clear
-	echo setup exiting...
+	if [ $WIFICHANGED = 1 ]; then
+		echo
+		echo "WIFI: $WIFI"
+		echo "SSID: $SSID"
+		echo "Password: $PASSWORD"
+		echo "Security: $ENCRYPTION"
+	fi
+	if [ $STATICIPCHANGED = 1 ]; then
+		echo
+		echo "Static IP: $STATUSIP"
+		echo "Static IP address: $IP"
+		echo "Netmask: $NETMASK"
+		echo "Broadcast: $BROADCAST"
+		echo "Default gateway: $GATEWAY"
+	fi
+	if [ $WEBGUICHANGED = 1 ]; then
+		echo
+		echo "Web GUI is $STATUS"
+	fi
+	echo
 	exit
 }
 
@@ -64,6 +90,7 @@ pcp_exit_program() {
 # Main menu
 #----------------------------------------------------------------------------------------
 pcp_main_menu() {
+	pcp_variables
 	OPTION=$(dialog \
 		--title         "Main Menu" \
 		--stdout \
@@ -72,23 +99,26 @@ pcp_main_menu() {
 		--menu          "Choose option:" \
 		0 0 0 \
 		\
-		"Wifi"          "Set wifi configuration" \
-		"Static IP"     "Set static IP (wired networks only)" \
-		"Webgui"        "Enable/disable web gui" \
-		)
+		"Wifi"          "Setup Wifi" \
+		"Static IP"     "Setup Static IP (wired networks only)" \
+		"WebGUI"        "Enable/Disable Web GUI" \
+	)
 
 	[ $? = $DIALOG_OK ] || pcp_exit_program
 
 	case $OPTION in
 		Wifi)
+			WIFICHANGED=1
 			pcp_wifi_menu
 			pcp_main_menu
 			;;
 		Static*)
+			STATICIPCHANGED=1
 			pcp_dhcp_menu
 			pcp_main_menu
 			;;
-		Webgui)
+		WebGUI)
+			WEBGUICHANGED=1
 			pcp_webgui_menu
 			;;
 	esac
@@ -98,94 +128,93 @@ pcp_main_menu() {
 # Webgui
 #----------------------------------------------------------------------------------------
 pcp_webgui_menu() {
-	OPTION=$(dialog \
-		--title         "Wegui Menu" \
-		--stdout \
-		--cancel-label  "Exit" \
-		--backtitle     "$BACKTITLE" \
-		--menu          "Choose option:" \
-		0 0 0 \
-		\
-		"Enable"        "Enable webgui" \
-		"Disable"       "Disable webgui" \
-		"Status"        "Webgui status" \
-	)
+	pcp_get_webgui_status
+	if [ $WEBGUI = 0 ]; then
+		STATUS=Enabled.
+		BUTTON=Disable
+	else
+		STATUS=Disabled.
+		BUTTON=Enable
+	fi
 
-	[ $? = $DIALOG_CANCEL ] && pcp_main_menu
+	dialog	--title       "WebGUI Menu" \
+			--yes-label   "$BUTTON" \
+			--no-label    "Exit" \
+			--backtitle   "$BACKTITLE" \
+			--yesno       "\nWeb GUI is $STATUS\n\n" \
+			0 0
+	RESULT=$?
 
-	case $OPTION in
-		Enable)
+	if [ $RESULT = $DIALOG_OK ]; then
+		if [ $BUTTON = "Enable" ]; then
 			pcp_webgui_enable
-			pcp_webgui_menu
-			;;
-		Disable)
+		else
 			pcp_webgui_disable
-			pcp_webgui_menu
-			;;
-		Status)
-			pcp_webgui_status
-			pcp_webgui_menu
-			;;
-	esac
+		fi
+		pcp_webgui_menu
+	fi
+
+	[ $RESULT = $DIALOG_CANCEL ] && pcp_main_menu
 }
 
 #----------------------------------------------------------------------------------------
-# Enable webgui
+# Enable webGUI
 #----------------------------------------------------------------------------------------
 pcp_webgui_enable() {
-	sudo /usr/local/etc/init.d/httpd start 2>&1 >/dev/null
-	sed -i '/httpd start/s/^#\+//' $PCPHOME/do_rebootstuff.sh 2>&1 >/dev/null
-	pcp_backup_nohtml 2>&1 >/dev/null
-
-	dialog	--title      "Webgui enabled" \
-			--backtitle  "$BACKTITLE" \
-			--msgbox     "\nWebgui has been enabled." \
-			7 40
+	sudo /usr/local/etc/init.d/httpd start >/dev/null 2>&1
+	sed -i '/httpd start/s/^#\+//' $PCPHOME/do_rebootstuff.sh >/dev/null 2>&1
+	pcp_backup_nohtml >/dev/null 2>&1
 }
 
 #----------------------------------------------------------------------------------------
-# Disable webgui
+# Disable webGUI
 #----------------------------------------------------------------------------------------
 pcp_webgui_disable() {
-	sudo /usr/local/etc/init.d/httpd stop 2>&1 >/dev/null
-	sed -i '/httpd start/s/^/#/g' $PCPHOME/do_rebootstuff.sh 2>&1 >/dev/null
-	pcp_backup_nohtml 2>&1 >/dev/null
-
-	dialog	--title      "Webgui disabled" \
-			--backtitle  "$BACKTITLE" \
-			--msgbox     "\nWebgui has been disabled." \
-			7 40
+	sudo /usr/local/etc/init.d/httpd stop >/dev/null 2>&1
+	sed -i '/httpd start/s/^/#/g' $PCPHOME/do_rebootstuff.sh >/dev/null 2>&1
+	pcp_backup_nohtml >/dev/null 2>&1
 }
 
 #----------------------------------------------------------------------------------------
-# Status webgui
+# Status webGUI
 #----------------------------------------------------------------------------------------
-pcp_webgui_status() {
-	MSG=$(echo
+pcp_get_webgui_status() {
+	WEBGUI=0
 	ps | grep -v grep | grep httpd
-	cat /home/tc/www/cgi-bin/do_rebootstuff.sh | grep init.d/httpd
-	echo)
-
-	dialog	--title      "Webgui status - DEBUG info" \
-			--backtitle  "$BACKTITLE" \
-			--msgbox     "$MSG" \
-			0 0
+	[ $? = 0 ] || WEBGUI=$(($WEBGUI + 1))
+	cat /home/tc/www/cgi-bin/do_rebootstuff.sh | grep "#/usr/local/etc/init.d/httpd"
+	[ $? = 0 ] && WEBGUI=$(($WEBGUI + 1))
 }
 
 #========================================================================================
 # Static IP
 #----------------------------------------------------------------------------------------
 pcp_dhcp_menu() {
-	dialog	--title      "DHCP Menu" \
-			--yes-label  "DHCP on" \
-			--no-label   "DHCP off" \
+	pcp_get_static_ip_status
+	[ $STATISIP = 0 ] && STATUSIP=on || STATUSIP=off
+
+	pcp_read_script
+
+	dialog	--title      "Static IP Status Menu" \
 			--backtitle  "$BACKTITLE" \
-			--yesno      "\nTurn <DCHP on> or <DHCP off>. \n\n\
-							To turn static IP on, select <DHCP off>. \n\
-							To turn static IP off, select <DHCP on>. \n\n" \
+			--yesno      "\nAre these Static IP settings correct? \n\n\
+							Static IP: $STATUSIP \n\n\
+							IP address: $IP \n\
+							Netmask: $NETMASK \n\
+							Broadcast: $BROADCAST \n\
+							Default gateway: $GATEWAY \n\n" \
 			0 0
 
-	if [ $? = $DIALOG_OK ]; then
+	[ $? = $DIALOG_OK ] && pcp_main_menu
+
+	dialog	--title      "Static IP On/Off Menu" \
+			--yes-label  "On" \
+			--no-label   "Off" \
+			--backtitle  "$BACKTITLE" \
+			--yesno      "\nTurn Static IP On or Off. \n\n" \
+			0 0
+
+	if [ $? = $DIALOG_CANCEL ]; then
 		pcp_edit_localboot delete
 		pcp_nodhcp_bootcode delete
 		pcp_main_menu
@@ -211,20 +240,39 @@ pcp_static_ip_menu() {
 		"Broadcast:"          3 1  "$BROADCAST"  3 20 15 0 \
 		"Default gateway:"    4 1  "$GATEWAY"    4 20 15 0 \
 		2>&1 1>&3)
-	result=$?
+	RESULT=$?
 	exec 3>&-
 	IP=$(echo ${VALUES} | awk -F, '{ print $1 }')
 	NETMASK=$(echo ${VALUES} | awk -F, '{ print $2 }')
 	BROADCAST=$(echo ${VALUES} | awk -F, '{ print $3 }')
 	GATEWAY=$(echo ${VALUES} | awk -F, '{ print $4 }')
 
-	if [ $result = $DIALOG_OK ]; then 
+	if [ $RESULT = $DIALOG_OK ]; then 
 		pcp_edit_localboot add
 		pcp_nodhcp_bootcode add
 		pcp_write_script
+		pcp_dhcp_menu
 	else
 		pcp_main_menu
 	fi
+}
+
+pcp_get_static_ip_status() {
+	STATISIP=0
+	[ -f $STATICIP ] || STATISIP=$(($STATISIP + 1))
+	grep eth0.sh /opt/bootlocal.sh
+	[ $? = 0 ] || STATISIP=$(($STATISIP + 1))
+	pcp_mount_mmcblk0p1_nohtml >/dev/null
+	if mount | grep $VOLUME >/dev/null; then
+		grep nodhcp /mnt/mmcblk0p1/cmdline.txt
+		[ $? = 0 ] || STATISIP=$(($STATISIP + 1))
+		pcp_umount_mmcblk0p1_nohtml >/dev/null
+	fi
+
+	dialog	--title      "Static IP Statis" \
+			--backtitle  "$BACKTITLE" \
+			--msgbox      "\n$STATISIP\n\n" \
+			0 0
 }
 
 #----------------------------------------------------------------------------------------
@@ -250,6 +298,7 @@ pcp_read_script() {
 # Write eth0 script
 #----------------------------------------------------------------------------------------
 pcp_write_script() {
+	sudo rm -f $STATICIP
 	sudo echo '#!/bin/sh' >$STATICIP
 	sudo echo '# Generated by piCorePlayer' >>$STATICIP
 	sudo echo 'echo "[ INFO ] Running $0..."' >>$STATICIP
@@ -264,9 +313,9 @@ pcp_write_script() {
 # Add/delete /opt/eth0.sh to bootlocal.sh
 #----------------------------------------------------------------------------------------
 pcp_edit_localboot() {
-	[ $DEBUG = 1 ] && echo '<p class="debug">[ DEBUG ] Writing /opt/bootlocal.sh...</p>'
+	[ $DEBUG = 1 ] && echo '[ DEBUG ] Writing /opt/bootlocal.sh...'
 	grep -v eth0.sh /opt/bootlocal.sh >/opt/bootlocal.sh~
-	sudo chmod 755 /opt/bootlocal.sh~
+	sudo chmod u=rwx,g=rx,o=rx /opt/bootlocal.sh~
 	sudo mv /opt/bootlocal.sh~ /opt/bootlocal.sh
 	[ $1 = "add" ] && sed -i "4i /opt/eth0.sh" /opt/bootlocal.sh
 }
@@ -275,14 +324,14 @@ pcp_edit_localboot() {
 # Add/delete nodhcp boot code to /mnt/mmcblk0p1/cmdline.txt
 #----------------------------------------------------------------------------------------
 pcp_nodhcp_bootcode() {
-	[ $DEBUG = 1 ] && echo '<p class="debug">[ DEBUG ] Writing /mnt/mmcblk0p1/cmdline.txt...</p>'
+	[ $DEBUG = 1 ] && echo '[ DEBUG ] Writing /mnt/mmcblk0p1/cmdline.txt...'
 	pcp_mount_mmcblk0p1_nohtml >/dev/null
 	if mount | grep $VOLUME >/dev/null; then
 		sed -i 's/nodhcp //g' /mnt/mmcblk0p1/cmdline.txt
 		[ $1 = "add" ] && sed -i 's/^/nodhcp /' /mnt/mmcblk0p1/cmdline.txt
 		pcp_umount_mmcblk0p1_nohtml >/dev/null
 	else
-		[ $DEBUG = 1 ] && echo '<p class="error">[ ERROR ] '$VOLUME' not mounted</p>'
+		[ $DEBUG = 1 ] && echo '[ ERROR ] '$VOLUME' not mounted'
 	fi
 }
 
@@ -292,22 +341,22 @@ pcp_nodhcp_bootcode() {
 pcp_wifi_menu() {
 	dialog	--title      "Wifi Status Menu" \
 			--backtitle  "$BACKTITLE" \
-			--yesno      "\nAre these settings correct? \n\n\
-							Wifi:	$WIFI \n\
-							SSID:	$SSID \n\
+			--yesno      "\nAre these Wifi settings correct? \n\n\
+							Wifi: $WIFI \n\n\
+							SSID: $SSID \n\
 							Password: $PASSWORD \n\
-							Security Mode: $ENCRYPTION \n" \
+							Security: $ENCRYPTION \n\n" \
 			0 0
 
 	if [ $? = $DIALOG_OK ]; then
 		pcp_write_wifi
 		pcp_main_menu
 	else
-		dialog	--title      "Wifi Menu" \
-				--yes-label  "Wifi on" \
-				--no-label   "Wifi off" \
+		dialog	--title      "Wifi On/Off Menu" \
+				--yes-label  "On" \
+				--no-label   "Off" \
 				--backtitle  "$BACKTITLE" \
-				--yesno      "\nTurn <Wifi on> or <Wifi off>. \n\n" \
+				--yesno      "\nTurn Wifi On or Off. \n\n" \
 				0 0
 
 		if [ $? = $DIALOG_OK ]; then
@@ -324,16 +373,16 @@ pcp_wireless_menu() {
 	exec 3>&1
 	VALUES=$(dialog \
 		--title            "Wireless Menu" \
-		--ok-label         "Save" \
-		--cancel-label     "Exit" \
+		--ok-label         "OK" \
+		--no-cancel \
 		--output-separator "," \
 		--backtitle        "$BACKTITLE" \
 		--form             "Setup Wifi" \
 		0 0 0 \
 		\
-		"SSID:"           1 1  "$SSID"        1 20 15 0 \
-		"Password:"       2 1  "$PASSWORD"    2 20 15 0 \
-		"Security Mode:"  3 1  "$ENCRYPTION"  3 20 15 0 \
+		"SSID:"                     1 1  "$SSID"        1 27 40 0 \
+		"Password:"                 2 1  "$PASSWORD"    2 27 40 0 \
+		"Security [WEP|WPA|OPEN]:"  3 1  "$ENCRYPTION"  3 27 4 0 \
 		2>&1 1>&3)
 	result=$?
 	exec 3>&-
@@ -343,20 +392,19 @@ pcp_wireless_menu() {
 
 	if [ $result = $DIALOG_OK ]; then 
 		case $ENCRYPTION in
-			WEP|WPA|None)
+			WEP|WPA|OPEN)
 				pcp_wifi_menu
 				;;
 			*)
 				dialog	--title      "Security Mode Error Message" \
 						--backtitle  "$BACKTITLE" \
 						--msgbox     "\nWARNING!!\n\
-								Security mode: $ENCRYPTION \n\
-								Security mode must be WEP, WPA or None.\n" \
+								Security: $ENCRYPTION \n\
+								Security must be WEP, WPA or OPEN.\n" \
 						0 0
 				pcp_wireless_menu
 				;;
 		esac
-		pcp_wifi_menu
 	else
 		pcp_main_menu
 	fi
