Further WPA wifi development
Introduced pcp_message that will handle colour, text and html messages.

diff --git a/www/cgi-bin/pcp-wifi-functions b/www/cgi-bin/pcp-wifi-functions
--- a/www/cgi-bin/pcp-wifi-functions
+++ b/www/cgi-bin/pcp-wifi-functions
@@ -1,6 +1,93 @@
 #!/bin/sh
 
-# Version: 4.0.0 2018-04-21
+# Version: 4.0.0 2018-04-22
+
+#========================================================================================
+# Load wifi extensions.
+#----------------------------------------------------------------------------------------
+pcp_message() {
+#	$1 = type: OK|INFO|ERROR|DEBUG
+#	$2 = message
+#	$3 = format: colour|text|html
+
+	MESSAGE=$2
+	case $1 in
+		OK|ok)
+			case $3 in
+				col*|COL*) echo "${GREEN}${MESSAGE}${NORMAL}" ;;
+				text|TEXT) echo '[ OK ] '${MESSAGE} ;;
+				html|HTML) echo '<p class="ok">[ OK ] '${MESSAGE}'</p>' ;;
+			esac
+		;;
+		INFO|info)
+			case $3 in
+				col*|COL*) echo "${YELLOW}${MESSAGE}${NORMAL}" ;;
+				text|TEXT) echo '[ INFO ] '${MESSAGE} ;;
+				html|HTML) echo '<p class="info">[ INFO ] '${MESSAGE}'</p>' ;;
+			esac
+		;;
+		ERROR|error)
+			case $3 in
+				col*|COL*) echo "${RED}${MESSAGE}${NORMAL}" ;;
+				text|TEXT) echo '[ ERROR ] '${MESSAGE} ;;
+				html|HTML) echo '<p class="error">[ ERROR ] '${MESSAGE}'</p>' ;;
+			esac
+		;;
+		DEBUG|debug)
+			case $3 in
+				col*|COL*) echo "${ORANGE}${MESSAGE}${NORMAL}" ;;
+				text|TEXT) echo '[ DEBUG ] '${MESSAGE} ;;
+				html|HTML) echo '<p class="debug">[ DEBUG ] '${MESSAGE}'</p>' ;;
+			esac
+		;;
+	esac
+}
+
+pcp_wifi_load_extn() {
+	# $1 - extension
+	# $2 - description
+	# $3 - colour|text|html
+
+	sudo -u tc pcp-load -i $1 >/dev/null 2>&1
+	if [ $? -eq 0 ]; then
+		pcp_message OK "$2 loaded." "$3"
+	else
+		pcp_message ERROR "$2 load error." "$3"
+	fi
+	sudo sed -i '/'$1'/d' $ONBOOTLST
+	sudo echo $1 >> $ONBOOTLST
+}
+
+#========================================================================================
+# Load wifi extensions.
+#----------------------------------------------------------------------------------------
+pcp_wifi_load_wifi_extns() {
+	# $1 - colour|text|html
+
+	pcp_message INFO "Loading wifi extensions..." "$1"
+
+	pcp_wifi_load_extn "wireless_tools.tcz" "Wireless tools" "$1"
+	pcp_wifi_load_extn "wpa_supplicant.tcz" "WPA supplicant" "$1"
+
+	pcp_message OK "Done." "$1"
+}
+
+#========================================================================================
+# Load wifi firmware extensions.
+#----------------------------------------------------------------------------------------
+pcp_wifi_load_wifi_firmware_extns() {
+	# $1 - format: colour|text|html
+
+	pcp_message INFO "Loading wifi firmware extensions..." "$1"
+
+	pcp_wifi_load_extn "firmware-atheros.tcz" "Atheros firmware" "$1"
+	pcp_wifi_load_extn "firmware-brcmwifi.tcz" "Broadcom USB firmware" "$1"
+	pcp_wifi_load_extn "firmware-ralinkwifi.tcz" "Ralink firmware" "$1"
+	pcp_wifi_load_extn "firmware-rtlwifi.tcz" "Realtek firmware" "$1"
+	pcp_wifi_load_extn "firmware-rpi3-wireless.tcz" "RPi Broadcom firmware" "$1"
+
+	pcp_message OK "Done." "$1"
+}
 
 #========================================================================================
 # Read wifi settings from current wpa_supplicant.conf
@@ -43,7 +130,7 @@ pcp_wifi_read_wpa_supplicant() {
 }
 
 #========================================================================================
-# Read wifi settings from newconfig.cfg <=== NOT USED YET
+# Read wifi settings from newconfig.cfg <=== NOT USED YET. NOT TESTED.
 #----------------------------------------------------------------------------------------
 pcp_wifi_read_newconfig() {
 	unset WPA_SSID WPA_PASSWORD WPA_PW KEY_MGMT WPA_ENCRYPTION
@@ -103,49 +190,25 @@ pcp_wifi_write_wpa_supplicant() {
 }
 
 #========================================================================================
-# Load wifi extensions.
-#----------------------------------------------------------------------------------------
-pcp_wifi_load_extensions() {
-	echo "${GREEN}Loading wifi extensions...${NORMAL}"
-	sudo -u tc tce-load -i wireless_tools.tcz >/dev/null 2>&1
-	[ $? -eq 0 ] && echo "${YELLOW}  Wireless tools loaded.${NORMAL}" || echo "${RED}  Wireless tools load error.${NORMAL}"
-	sudo -u tc tce-load -i wpa_supplicant.tcz >/dev/null 2>&1
-	[ $? -eq 0 ] && echo -n "${YELLOW}  wpa supplicant loaded.${NORMAL}" || echo -n "${RED}  wpa supplicant load error.${NORMAL}"
-	echo "${GREEN} Done.${NORMAL}"
-}
-
-#========================================================================================
-# Load wifi firmware extensions.
-#----------------------------------------------------------------------------------------
-pcp_wifi_load_firmware() {
-	echo "${GREEN}Loading wifi firmware...${NORMAL}"
-	sudo -u tc tce-load -i wifi.tcz >/dev/null 2>&1
-	[ $? -eq 0 ] && echo "${YELLOW}  Wifi modules loaded.${NORMAL}" || echo "${RED}  Wifi modules load error.${NORMAL}"
-	sudo -u tc tce-load -i firmware-atheros.tcz >/dev/null 2>&1
-	[ $? -eq 0 ] && echo "${YELLOW}  Atheros firmware loaded.${NORMAL}" || echo "${RED}  Atheros firmware load error.${NORMAL}"
-	sudo -u tc tce-load -i firmware-brcmwifi.tcz >/dev/null 2>&1
-	[ $? -eq 0 ] && echo "${YELLOW}  Broadcom USB firmware loaded.${NORMAL}" || echo "${RED}  Broadcom USB firmware load error.${NORMAL}"
-	sudo -u tc tce-load -i firmware-ralinkwifi.tcz >/dev/null 2>&1
-	[ $? -eq 0 ] && echo "${YELLOW}  Ralink firmware loaded.${NORMAL}" || echo "${RED}  Ralink firmware load error.${NORMAL}"
-	sudo -u tc tce-load -i firmware-rtlwifi.tcz >/dev/null 2>&1
-	[ $? -eq 0 ] && echo "${YELLOW}  Realtek firmware loaded.${NORMAL}" || echo "${RED}  Realtek firmware load error.${NORMAL}"
-	sudo -u tc tce-load -i firmware-rpi3-wireless.tcz >/dev/null 2>&1
-	[ $? -eq 0 ] && echo "${YELLOW}  RPi Broadcom firmware loaded.${NORMAL}" || echo "${RED}  RPi Broadcom firmware load error.${NORMAL}"
-	echo "${GREEN} Done.${NORMAL}"
-}
-
-#========================================================================================
 # Check all wifi extensions are installed.
 #----------------------------------------------------------------------------------------
 pcp_wifi_extension_installed() {
-	[ $(pcp_extn_is_installed $1) -eq 0 ] && echo $1' installed.' || echo $1' NOT installed.' 
+	# $1 - format: colour|text|html
+	# $2 - extension
+
+	if [ $(pcp_extn_is_installed $2) -eq 0 ]; then
+		pcp_message OK "$2 installed." "$1"
+	else
+		pcp_message ERROR "$2 not installed." "$1"
+	fi
 }
 
 pcp_wifi_all_extensions_installed() {
-	for i in wireless_tools wifi wpa_supplicant greg firmware-atheros firmware-brcmwifi firmware-ralinkwifi firmware-rtlwifi firmware-rpi3-wireless; do
-		echo -n '<p class="info">[ INFO ] '
-		pcp_wifi_extension_installed $i
-		echo '</p>'
+	EXTN_LIST="wireless_tools wpa_supplicant XXXx
+	firmware-atheros firmware-brcmwifi firmware-ralinkwifi firmware-rtlwifi firmware-rpi3-wireless"
+
+	for i in $EXTN_LIST; do
+		pcp_wifi_extension_installed "html" $i
 	done
 }
 
@@ -153,8 +216,9 @@ pcp_wifi_all_extensions_installed() {
 # Generate WPA passphrase from SSID and password.
 #----------------------------------------------------------------------------------------
 pcp_wifi_generate_passphrase() {
-	pcp_debug_variables WPA_PASSWORD WPA_ENCRYPTION WPA_PASSPHRASE
-	[ $DEBUG -eq 1 ] && echo '<p class="debug">[ DEBUG ] Generating new passphrase...</p>'
+	pcp_debug_variables "text" WPA_PASSWORD WPA_ENCRYPTION WPA_PASSPHRASE
+
+	[ $DEBUG -eq 1 ] && pcp_message DEBUG "Generating new passphrase..." "$1"
 	if [ "$WPA_PASSWORD" != "" ] && [ "$WPA_ENCRYPTION" = "WPA-PSK" ]; then
 		WPA_PASSPHRASE="$(wpa_passphrase $WPA_SSID $WPA_PASSWORD)"
 		if [ $? -eq 0 ]; then
@@ -166,7 +230,8 @@ pcp_wifi_generate_passphrase() {
 			WPA_PASSPHRASE="[ ERROR ] Password has not been set."
 		fi
 	fi
-	pcp_debug_variables WPA_PASSWORD WPA_ENCRYPTION WPA_PASSPHRASE
+
+	pcp_debug_variables "text" WPA_PASSWORD WPA_ENCRYPTION WPA_PASSPHRASE
 }
 
 #========================================================================================
