Updated ccs. Removed in-line -style:color="white" from html.

diff --git a/www/cgi-bin/pcp-functions b/www/cgi-bin/pcp-functions
--- a/www/cgi-bin/pcp-functions
+++ b/www/cgi-bin/pcp-functions
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-# Version: 6.0.0 2019-08-13
+# Version: 6.0.0 2019-08-16
 
 #========================================================================================
 # Setup debug logging
@@ -168,33 +168,42 @@ pcp_message() {
 #	FORMAT: colour|text|html
 	local FORMAT=$3
 
+	[ "$4" = "-n" ] && local SLASHP="" || local SLASHP="</p>"
+
 	case $TYPE in
 		OK|ok)
 			case $FORMAT in
-				col*|COL*) echo "${GREEN}${MESSAGE}${NORMAL}" ;;
-				text|TEXT) echo '[ OK ] '${MESSAGE} ;;
-				html|HTML) echo '<p class="ok">[ OK ] '${MESSAGE}'</p>' ;;
+				col*|COL*) echo $4 "${GREEN}${MESSAGE}${NORMAL}" ;;
+				text|TEXT) echo $4 '[ OK ] '${MESSAGE} ;;
+				html|HTML) echo '<p class="ok">[ OK ] '${MESSAGE}${SLASHP} ;;
 			esac
 		;;
 		INFO|info)
 			case $FORMAT in
-				col*|COL*) echo "${YELLOW}${MESSAGE}${NORMAL}" ;;
-				text|TEXT) echo '[ INFO ] '${MESSAGE} ;;
-				html|HTML) echo '<p class="info">[ INFO ] '${MESSAGE}'</p>' ;;
+				col*|COL*) echo $4 "${YELLOW}${MESSAGE}${NORMAL}" ;;
+				text|TEXT) echo $4 '[ INFO ] '${MESSAGE} ;;
+				html|HTML) echo '<p class="info">[ INFO ] '${MESSAGE}${SLASHP} ;;
 			esac
 		;;
 		ERROR|error)
 			case $FORMAT in
-				col*|COL*) echo "${RED}${MESSAGE}${NORMAL}" ;;
-				text|TEXT) echo '[ ERROR ] '${MESSAGE} ;;
-				html|HTML) echo '<p class="error">[ ERROR ] '${MESSAGE}'</p>' ;;
+				col*|COL*) echo $4 "${RED}${MESSAGE}${NORMAL}" ;;
+				text|TEXT) echo $4 '[ ERROR ] '${MESSAGE} ;;
+				html|HTML) echo '<p class="error">[ ERROR ] '${MESSAGE}${SLASHP} ;;
 			esac
 		;;
 		DEBUG|debug)
 			case $FORMAT in
-				col*|COL*) echo "${ORANGE}${MESSAGE}${NORMAL}" ;;
-				text|TEXT) echo '[ DEBUG ] '${MESSAGE} ;;
-				html|HTML) echo '<p class="debug">[ DEBUG ] '${MESSAGE}'</p>' ;;
+				col*|COL*) echo $4 "${ORANGE}${MESSAGE}${NORMAL}" ;;
+				text|TEXT) echo $4 '[ DEBUG ] '${MESSAGE} ;;
+				html|HTML) echo '<p class="debug">[ DEBUG ] '${MESSAGE}${SLASHP} ;;
+			esac
+		;;
+		WARN|warn)
+			case $FORMAT in
+				col*|COL*) echo $4 "${ORANGE}${MESSAGE}${NORMAL}" ;;
+				text|TEXT) echo $4 '[ WARN ] '${MESSAGE} ;;
+				html|HTML) echo '<p class="debug">[ WARN ] '${MESSAGE}${SLASHP} ;;
 			esac
 		;;
 	esac
@@ -453,33 +462,29 @@ pcp_mac_address() {
 }
 
 pcp_wlan0_mac_address() {	# <== GE depreciated
-	# The wireless MAC address (if installed)
-#	ifconfig wlan0 2>&1 | grep -o -E '([[:xdigit:]]{1,2}:){5}[[:xdigit:]]{1,2}' | tr '[A-Z]' '[a-z]'
 	pcp_mac_address "wlan0"
 }
 
 pcp_eth0_mac_address() {	# <== GE depreciated
-	# The physical MAC address of Raspberry Pi
-#	ifconfig eth0 2>&1 | grep -o -E '([[:xdigit:]]{1,2}:){5}[[:xdigit:]]{1,2}' | tr '[A-Z]' '[a-z]'
 	pcp_mac_address "eth0"
 }
 
 pcp_controls_mac_address() {
 	ifconfig eth0 2>&1 | grep inet >/dev/null 2>&1
-	eth0_IP=$?
+	local eth0_IP=$?
 	ifconfig wlan0 2>&1 | grep inet >/dev/null 2>&1
-	wlan0_IP=$?
-	PLAYER_MAC=$(pcp_eth0_mac_address)
+	local wlan0_IP=$?
+	local PLAYER_MAC=$(pcp_eth0_mac_address)
 	if [ "$WIFI" = "on" ]; then
 		if [ $wlan0_IP -eq 0 ]; then
-			PLAYER_MAC=$(pcp_wlan0_mac_address)
+			local PLAYER_MAC=$(pcp_wlan0_mac_address)
 		fi
 		if [ $eth0_IP -eq 0 ]; then
-			PLAYER_MAC=$(pcp_eth0_mac_address)
+			local PLAYER_MAC=$(pcp_eth0_mac_address)
 		fi
 	fi
 	if [ $(pcp_config_mac_address) ]; then
-		PLAYER_MAC=$(pcp_config_mac_address)
+		local PLAYER_MAC=$(pcp_config_mac_address)
 	fi
 	echo $PLAYER_MAC
 }
@@ -593,7 +598,7 @@ pcp_navigation() {
 		echo '          <table class="bggrey percent100">'
 		echo '            <tr class="warning">'
 		echo '              <td>'
-		echo '                <p style="color:white"><b>Warning:</b> A reboot is required to complete changes.&nbsp;&nbsp;'
+		echo '                <p><b>Warning:</b> A reboot is required to complete changes.&nbsp;&nbsp;'
 		echo '                  <input type="button" value="Reboot" onClick="javascript:pcp_confirm('\''Reboot '$NAME?''\'','\''main.cgi?ACTION=reboot'\'')" />'
 		echo '                </p>'
 		echo '              </td>'
@@ -1218,7 +1223,7 @@ pcp_redirect_button() {
 #  - $1 can be set to "nohtml"
 #  - function can generate text or html output.
 #----------------------------------------------------------------------------------------
-pcp_backup() {
+xxxpcp_backup() {
 	WARNSIZE=350000
 	if [ "$1" = "nohtml" ]; then
 		NEWLINE="-n"
@@ -1269,6 +1274,52 @@ pcp_backup() {
 		echo $PCLASSWARN'[ WARN ] Your backup is a little large - '$(pcp_check_mydata)' bytes.'$SLASHP | tee -a $LOG
 		echo $PCLASSINFO'[ INFO ] Be careful adding large files to /home/tc.'$SLASHP | tee -a $LOG
 		echo $PCLASSINFO'[ INFO ] If your backup takes a long time, piCorePlayer may fail to start properly.'$SLASHP | tee -a $LOG
+	fi
+}
+
+pcp_backup() {
+	local FORMAT=$1
+	local WARNSIZE=35 #0000
+	[ "$FORMAT" = "nohtml" ] && local FORMAT="text" # <== GE nohtml depreciated
+	[ "$FORMAT" = "" ] && local FORMAT="html"
+
+	# Delete any previous backup_done file
+	[ -e /tmp/backup_done ] && sudo rm -f /tmp/backup_done
+
+	# Do a backup - filetool.sh backs up files in .filetool.lst
+	pcp_message INFO "" $FORMAT "-n"
+	pcp_message INFO "" "text" "-n" >> $LOG
+	sudo filetool.sh -b | tee -a $LOG
+#	[ "$1" = "nohtml" ] || echo $SLASHP
+	sync > /dev/null 2>&1
+
+	# If backup_status file exists and is non-zero in size, then an error has occurred
+	if [ -s /tmp/backup_status ]; then
+		pcp_message ERROR "Show backup_status..." $FORMAT
+		pcp_message ERROR "Show backup_status..." "text" >> $LOG
+		echo $NEWLINE $PRE
+		cat /tmp/backup_status | tee -a $LOG
+		echo $NEWLINE $SLASHPRE
+	fi
+
+	# If backup_done exists, then the backup was successful
+	if [ -f /tmp/backup_done ]; then
+		pcp_message OK "Backup successful." $FORMAT
+		pcp_message OK "Backup successful." "text" >> $LOG
+	else
+		pcp_message ERROR "Backup failed." $FORMAT
+		pcp_message ERROR "Backup failed." "text" >> $LOG
+	fi
+
+	# Encourage users to keep files backed up to mydata.tgz small
+	if [ $(pcp_check_mydata) -gt $WARNSIZE ]; then
+		pcp_message WARN "Your backup is a little large - $(pcp_check_mydata) bytes." $FORMAT
+		pcp_message INFO "Be careful adding large files to /home/tc." $FORMAT
+		pcp_message INFO "If your backup takes a long time, piCorePlayer may fail to start properly." $FORMAT
+
+		pcp_message WARN "Your backup is a little large - $(pcp_check_mydata) bytes." "text" >> $LOG
+		pcp_message INFO "Be careful adding large files to /home/tc." "text" >> $LOG
+		pcp_message INFO "If your backup takes a long time, piCorePlayer may fail to start properly." "text" >> $LOG
 	fi
 }
 
