Further WPA wifi development

diff --git a/www/cgi-bin/pcp-wifi-functions b/www/cgi-bin/pcp-wifi-functions
--- a/www/cgi-bin/pcp-wifi-functions
+++ b/www/cgi-bin/pcp-wifi-functions
@@ -3,7 +3,7 @@
 # Version: 4.0.0 2018-04-22
 
 #========================================================================================
-# Load wifi extensions.
+# Messages.
 #----------------------------------------------------------------------------------------
 pcp_message() {
 #	$1 = type: OK|INFO|ERROR|DEBUG
@@ -197,6 +197,21 @@ pcp_wifi_write_wpa_supplicant() {
 }
 
 #========================================================================================
+# Does wpa_supplicant.conf exist?
+#----------------------------------------------------------------------------------------
+pcp_exists_wpa_supplicant() {
+	[ -f $WPASUPPLICANTCONF ] && echo 0 || echo 1
+}
+
+#========================================================================================
+# Was wpa_supplicant.conf generated by piCorePlayer?
+#----------------------------------------------------------------------------------------
+pcp_wifi_generated_by_pcp() {
+	RESULT=$(grep "^# Generated by piCorePlayer" $WPASUPPLICANTCONF)
+	echo $?
+}
+
+#========================================================================================
 # Check all wifi extensions are installed.
 #----------------------------------------------------------------------------------------
 pcp_wifi_extension_installed() {
@@ -225,7 +240,7 @@ pcp_wifi_all_extensions_installed() {
 pcp_wifi_generate_passphrase() {
 	pcp_debug_variables "text" WPA_PASSWORD WPA_ENCRYPTION WPA_PASSPHRASE
 
-	[ $DEBUG -eq 1 ] && pcp_message DEBUG "Generating new passphrase..." "$1"
+	pcp_message INFO "Generating new passphrase..." "$1"
 	if [ "$WPA_PASSWORD" != "" ] && [ "$WPA_ENCRYPTION" = "WPA-PSK" ]; then
 		WPA_PASSPHRASE="$(wpa_passphrase $WPA_SSID $WPA_PASSWORD)"
 		if [ $? -eq 0 ]; then
@@ -240,6 +255,115 @@ pcp_wifi_generate_passphrase() {
 
 	pcp_debug_variables "text" WPA_PASSWORD WPA_ENCRYPTION WPA_PASSPHRASE
 }
+
+#========================================================================================
+# (c) Robert Shingledecker 2011-2012 v1.4
+# This routine has been based on code from the piCore script wifi.sh
+# /usr/local/bin/wifi.sh
+#----------------------------------------------------------------------------------------
+pcp_wifi_available_networks() {
+	unset WIFI2 && CNT=0
+	echo -en "Scanning"
+	until [ -n "$WIFI2" ]
+	do
+		[ $((CNT++)) -gt 5 ] && break || sleep 1
+		echo -en "."
+		WIFI2="$(iwconfig 2>/dev/null | awk '{if (NR==1)print $1}')"
+	done
+	if [ -z "$WIFI2" ]; then
+		echo -en "\n\nNo wifi devices found!\n\n"
+		echo -en "Possible error:\n\n"
+		echo -en "1. USB wifi adapter missing - insert adapter.\n"
+		echo -en "2. wifi drivers and firmware missing - reboot required."
+		echo '</textarea>'
+		echo '                </td>'
+		echo '              </tr>'
+		echo '            </table>'
+		echo '          </fieldset>'
+		echo '        </div>'
+#		echo '      </form>'
+		echo '    </td>'
+		echo '  </tr>'
+		echo '</table>'
+		pcp_html_end
+	fi
+	ifconfig "$WIFI2" up 2>/dev/null
+	(for i in `seq 5`
+	do
+		iwlist "$WIFI2" scanning
+		[ $? -eq 0 ] && break
+		sleep 1
+	done ) | awk -v wifi=$WIFI2 '
+	BEGIN {
+		RS="\n"
+		FS=":"
+		i = 0
+	}
+	function rsort(qual,level,sid,enc,chan,freq,type,addr,n,i,j,t) {
+		for (i = 2; i <= n; i++)
+			for (j = i; j > 1 && qual[j]+0 > qual[j-1]+0; j--) {
+				# swap qual[j] and qual[j-1]
+				t = qual[j]; qual[j] = qual[j-1]; qual[j-1] = t
+				t = level[j]; level[j] = level[j-1]; level[j-1] = t
+				t = sid[j];  sid[j]  = sid[j-1];  sid[j-1]  = t
+				t = enc[j];  enc[j]  = enc[j-1];  enc[j-1]  = t
+				t = chan[j]; chan[j] = chan[j-1]; chan[j-1] = t
+				t = freq[j]; freq[j] = freq[j-1]; freq[j-1] = t
+				t = type[j]; type[j] = type[j-1]; type[j-1] = t
+				t = addr[j]; addr[j] = addr[j-1]; addr[j-1] = t
+			}
+	}
+	# main ()
+	{
+		if ($1 ~ /Cell/) {
+			if ( i == 0 || sid[i] != "" ) i++
+			addr[i] = $2":"$3":"$4":"$5":"$6":"$7
+			gsub(" ","",addr[i])
+		}
+		if ($1 ~ /Frequency/) {
+			split($2,c," ")
+			chan[i] = c[4]
+			gsub("\)","",chan[i])
+			freq[i] = "("c[1]c[2]")"
+			gsub(" ","",freq[i])
+		}
+		if ($1 ~ /Quality/) {
+			if (index($1,"=")) {
+				split($1,c,"=")
+				q = c[2]
+				level[i] = c[3]
+				gsub(" ","",level[i])
+			}
+			split(q,c,"/")
+			qual[i] = c[1] * 100 / c[2]
+		}
+		if ($1 ~ /Encryption/) {
+			enc[i] = $2
+		}
+		if ($1 ~ /ESSID/) {
+			sid[i] = $2
+			gsub("\"","",sid[i])
+		}
+		if (enc[i] ~ /off/) type[i]="NONE"
+		if ($2 ~ /WPA/) type[i]="WPA"
+		if ($2 ~ /WPA2 /) type[i]="WPA2"
+		if (type[i] == "" ) type[i]="WEP"
+	}
+	END {
+		rsort(qual,level,sid,enc,chan,freq,type,addr,NR)
+		print ""
+		print "---------------------------------------------------------------------------------------------"
+		print "       SSID                 Quality   Level       Channel      Encryption       Address"
+		print "---------------------------------------------------------------------------------------------"
+		for (l=1; l<15; l++) {
+			++j
+			#                     |NO. |SSID |Qual  |Level |Channel   |Encrypt   |Address
+			if ( j <= i ) printf "%2d. %-25s %3d    %7s    %2d %10s   %-3s %-4s  %18s\n", j, sid[j], qual[j], level[j], chan[j], freq[j], enc[j], type[j], addr[j]
+		}
+		print "---------------------------------------------------------------------------------------------"
+	} '
+}
+#----------------------------------------------------------------------------------------
 
 #========================================================================================
 # wifi extensions and dependencies.
